### ISSUE TITLE
How can I config multi drupal site? 

### ISSUE THREAD

**Issue by pantasio** [geerlingguy/ansible-role-drupal#18]
I wanna config defaults/main.yml  wtih diffence var..
Ex:  
site1: 
drupal_core_version: "7.30"
drupal_domain: "prod.example.org"
...etc...

site2:
drupal_core_version: "7.41"
drupal_domain: "dev.example.org"
.... etc ....

I dont want to config defaults/main.yml again and again, this is not unmanaged...

I wanna use Looping over Parallel Sets of Data at website http://docs.ansible.com/ansible/playbooks_loops.html#id18
for managed vars each site
but unsuccessful

sorry my English..

**Comment by oxyc** [comment]
This is currently not supported. But @geerlingguy has mentioned he's considering adding support for it https://github.com/geerlingguy/drupal-vm/issues/449#issuecomment-185560269

**Comment by geerlingguy** [comment]
It's not _officially_ supported (e.g. it's not something that's automatically setup), but you can do multiple Drupal installs (by adding a docroot/synced folder/vhost for each site) or even multisite drupal (pointing a bunch of vhosts at one docroot/synced folder).

See the docs: http://docs.drupalvm.com/en/latest/deployment/multisite/

**Comment by geerlingguy** [comment]
Also, I plan on working on this as part of the `geerlingguy.drupal` role then using that role to loop through configured sites... but there are a couple small bugs in Ansible 2.0.x currently that prevent this from working as cleanly as I'd like.

**Comment by geerlingguy** [comment]
Silly me... forgot which GitHub project this is in—yes, I plan on adding functionality to this role... for now, you might be able to add the role with a with loop and get it working depending on the version of Ansible you're using, e.g.:

```yaml
- hosts: all
  roles:
    - role: geerlingguy.drupal
      with_items:
        - drupal_core_version: "8.0.x"
          drupal_core_path: "/var/www/drupal1"
          ...
        - drupal_core_version: "8.0.x"
          drupal_core_path: "/var/www/drupal1"
          ...
```
