### ISSUE TITLE
library to use drupal variables inside a playbook

### ISSUE THREAD

**Issue by drzraf** [geerlingguy/ansible-role-drupal#19]
Goal :
```yaml
- name: install Drupal module X
  command: drush dl securelogin
  when: ansible_local["{{ 'drupal-modules.json' }}"]['securelogin'] is not defined
```

For this to work variables and modules needs to be stored as Ansible facts.
Since this is a costly process, this should not happen at every run, but only when they change (Drupal & somehow MySQL keep a trace of that)

The following fact file does exactly that, given a drush alias :
```yml
- name: ansible custom facts directory
  file: state=directory recurse=yes path=/etc/ansible/facts.d

# should be done only if variable UPDATE_TIME > stat of the fact file
# but... https://bugs.mysql.com/bug.php?id=18229
# UPDATE_TIME isn't supported for InnoDB

# Thus the alternative:


#### facts about variables
- name: last time Drupal variables where modified
  command: drush {{ drupal_alias }} sqlq --extra=-N "SELECT created FROM cache_bootstrap WHERE cid = 'variables' LIMIT 1"
  register: last_variables_update
  changed_when: False
  sudo: no

- name: last time Drupal variables where registered
  stat: path="{{ '/etc/ansible/facts.d/drupal-variables' ~ drupal_alias ~ '.json.fact' }}"
  register: last_variables_registration

- name: store drupal variables for "{{ drupal_alias }}"
  shell: drush {{ drupal_alias|quote }} --format=json vget > "{{ '/tmp/drupal-variables' ~ drupal_alias ~ '.json.fact' }}"
  sudo: no
  # if cache_bootstrap does not contains variables, it may have just been updated recently
  when: last_variables_update|failed or last_variables_registration.stat.mtime is not defined or (last_variables_update.stdout|int() > last_variables_registration.stat.mtime|int())

- name: move drupal variables for "{{ drupal_alias }}" to fact-directory
  command: removes="{{ '/tmp/drupal-variables' ~ drupal_alias ~ '.json.fact' }}" mv "{{ '/tmp/drupal-variables' ~ drupal_alias ~ '.json.fact' }}" "{{ '/etc/ansible/facts.d/drupal-variables' ~ drupal_alias ~ '.json.fact' }}"


#### facts about modules
- name: last time Drupal modules where modified
  command: drush {{ drupal_alias }} sqlq --extra=-N "SELECT timestamp FROM watchdog WHERE type = 'system' AND message LIKE '\%module%' ORDER BY wid desc limit 1;"
  register: last_modules_update
  changed_when: False
  sudo: no

- name: last time Drupal modules where registered
  stat: path="{{ '/etc/ansible/facts.d/drupal-modules' ~ drupal_alias ~ '.json.fact' }}"
  register: last_modules_registration

- name: store drupal modules for "{{ drupal_alias }}"
  shell: drush {{ drupal_alias|quote }} --format=json pmi > "{{ '/tmp/drupal-modules' ~ drupal_alias ~ '.json.fact' }}" 2>/dev/null
  sudo: no
  when: last_modules_update|failed or last_modules_registration.stat.mtime is not defined or (last_modules_update.stdout|int() > last_modules_registration.stat.mtime|int())

- name: move store drupal modules for "{{ drupal_alias }}" to fact-directory
  command: removes="{{ '/tmp/drupal-modules' ~ drupal_alias ~ '.json.fact' }}" mv "{{ '/tmp/drupal-modules' ~ drupal_alias ~ '.json.fact' }}" "{{ '/etc/ansible/facts.d/drupal-modules' ~ drupal_alias ~ '.json.fact' }}"


#### finally
- name: chown/chmod drupal facts in /etc/ansible/facts.d/{{ "drupal-*" ~ drupal_alias }}.json.fact
  file: path="/etc/ansible/facts.d/{{ item }}.json.fact" owner=root group=root mode=0640
  with_items:
    - "{{ 'drupal-variables' ~ drupal_alias }}"
    - "{{ 'drupal-modules' ~ drupal_alias }}"

- name: re-read facts after adding custom fact(s)
  setup: filter=ansible_local
  when: last_variables_registration.stat.mtime is not defined or last_modules_registration.stat.mtime is not defined or last_variables_update.stdout|int > last_variables_registration.stat.mtime|int or last_modules_update.stdout|int > last_modules_registration.stat.mtime|int
```

Then using variables by :
```yaml
- name: do blah
  command: drush "{{ drupal_alias }}" blah
  sudo: no
  when: ansible_local["{{ 'drupal-variables' ~ drupal_alias ~ '.json' }}"]['blah'] is not defined


An alternative could be to write a Drush module for that which would determinate if variables/modules changed significantly to be worth the rewrite then handle export and write to /etc.
The task file would just have to run this drush command every time and re-read facts in order to benefit from Drupal variables/modules.

Should this be a library?
