### ISSUE TITLE
Get rid of soft dependency on geerlingguy.php role

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-drupal#35]
Currently this role calls the `restart webserver` handler in the `geerlingguy.php` role when a Drupal deployment is completed, but this role _shouldn't_, since that role is not a hard dependency.

In the PHP role, the handlers defined are:

```yaml
- name: restart webserver
  service:
    name: "{{ php_webserver_daemon }}"
    state: restarted
  notify: restart php-fpm
  when: php_enable_webserver

- name: restart php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
  when: php_enable_php_fpm
```

We could either define our own handler(s), or figure out whether it's strictly necessary or not. I think the reason I had that in there initially was for the Raspberry Pi-based setup I tested on—I had opcache configured to _not_ stat files on every page load since the files were on slow microSD cards... for most servers (and by default), since opcache is looking at each file, we technically don't need a hard restart of php-fpm to pick up changed files.
