### ISSUE TITLE
Get rid of soft dependency on geerlingguy.drush role

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-drupal#39]
This role currently uses the `{{ drush_path }}` variable in a number of places. That variable may not be set if someone's not using the `geerlingguy.drush` role!

Therefore, it would be a good idea to maybe set it as a default like:

```yaml
- name: Set Drush path if not already configured.
  set_fact:
    drush_path: drush
  when: drush_path is not defined
```

Totally untested, but it seems like that would work.

Related to work in https://github.com/geerlingguy/ansible-role-drupal/pull/37
