### ISSUE TITLE
setting drupal_core_owner and drupal_core_owner_become causes my playbook to fail

### ISSUE THREAD

**Issue by huntertj** [geerlingguy/ansible-role-drupal#82]
## Description
When I use drupal_core_owner and drupal_core_owner_become the playbook fails on Install dependencies with composer require (this may take a while). with unable to write composer.json

## Steps to Reproduce
Set drupal_core_owner to something other then the user running the playbook, set drupal_core_owner_become to true
run the playbook

## Actual Behavior
task fail with permission issues

## Expected Behavior
Expected the playbook to complete and utilize drupal_core_owner as needed

## Notes
adding to roles/geerlingguy.drupal/tasks/build-composer-project.yml fixes this for me
```
- name: Install dependencies with composer require (this may take a while).
  composer:
    command: require
    arguments: "{{ item }}"
    working_dir: "{{ drupal_composer_install_dir }}"
  with_items: "{{ drupal_composer_dependencies|default([]) }}"
  become: "{{ drupal_core_owner_become }}"
  become_user: "{{ drupal_core_owner }}"
```
