### ISSUE TITLE
Make composer a dependency

### ISSUE THREAD

**Issue by cjohannsen81** [geerlingguy/ansible-role-drupal#88]
When `drupal_build_composer_project: true` is set in the role, the `composer_path` variable is used from the Composer role.

```
- name: Install dependencies with composer require (this may take a while).
  command: "{{ composer_path }} require {{ item }} -d {{ drupal_composer_install_dir }}"
  register: composer_require_result
  changed_when: "'Nothing to install' not in composer_require_result.stderr"
  with_items: "{{ drupal_composer_dependencies|default([]) }}"
  become: false
  environment:
    COMPOSER_PROCESS_TIMEOUT: 1200
    COMPOSER_MEMORY_LIMIT: '-1'
```
